apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexora-postgres
  namespace: nexora
  labels:
    app: nexora-postgres
    app.kubernetes.io/name: nexora-postgres
    app.kubernetes.io/part-of: nexora-platform
spec:
  serviceName: nexora-postgres
  replicas: 1
  selector:
    matchLabels:
      app: nexora-postgres
  template:
    metadata:
      labels:
        app: nexora-postgres
        app.kubernetes.io/name: nexora-postgres
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "nexora"
            - name: POSTGRES_USER
              value: "nexora"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexora-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "nexora", "-d", "nexora"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "nexora", "-d", "nexora"]
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql.conf
              subPath: postgresql.conf
      volumes:
        - name: postgres-config
          configMap:
            name: nexora-postgres-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
        storageClassName: standard
