apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexora-redis
  namespace: nexora
  labels:
    app: nexora-redis
    app.kubernetes.io/name: nexora-redis
    app.kubernetes.io/part-of: nexora-platform
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nexora-redis
  template:
    metadata:
      labels:
        app: nexora-redis
        app.kubernetes.io/name: nexora-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              protocol: TCP
              name: redis
          args: ["/usr/local/etc/redis/redis.conf"]
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
      volumes:
        - name: redis-config
          configMap:
            name: nexora-redis-config
        - name: redis-data
          emptyDir: {}
